# Generated by Django 4.1 on 2022-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='files',
            field=models.FileField(upload_to='media'),
        ),
    ]
